#!/bin/bash
apt-get update -y
hostnamectl set-hostname one.venketraman.com
ufw allow 22,80,443,4443,9001/tcp
ufw allow 10000/udp
ufw enable
ufw status verbose
apt install apt-transport-https
apt-add-repository universe
apt-get update -y
curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'
echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
apt-get update -y
add-apt-repository ppa:certbot/certbot

//sudo apt install jitsi-meet // during instaltion give the domain of your meeting server
//sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh //during the instaltion its asks mail id for communication
